services:

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

  redis-cache:
    image: redis-cache
    container_name: redis-cache
    build:
      context: ./requirements/bonus/redis-cache
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - wordpress
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - mariadb
      - wordpress
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    restart: always

  website:
    image: website
    container_name: website
    build:
      context: ./requirements/bonus/website
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - inception
    restart: always
    

  wordpress:
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - mariadb
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html/wordpress
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
      
  ftp-server:
    image: ftp-server
    container_name: ftp-server
    build:
      context: ./requirements/bonus/FTP-server
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - wordpress
    env_file:
      - ./.env
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    restart: always

  cadvisor:
    image: cadvisor
    container_name: cadvisor
    depends_on:
      - mariadb
      - wordpress
      - nginx
      - website
      - adminer
      - ftp-server
      - redis-cache
    build:
      context: ./requirements/bonus/cadvisor
      dockerfile: Dockerfile
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - inception
    ports:
      - "8081:8080"
    restart: always

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/mariadb/
  wordpress:
    name: wordpress
    driver_opts:
      type: none
      o : bind
      device : $HOME/data/wordpress/
