version: '3.8'

services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./mynginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db
    networks:
      - inception  

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception

networks:
  inception:

volumes:
  wordpress_data:
  db_data:
