version: '3.3'

services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    image: nginx
    build:
      context: ./srcs/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - inception

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - mariadb
    # build:
    #   context: ./srcs/wordpress
    #   dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - wordpress_html:/var/www/html
    networks:
      - inception

  mariadb:
    image: mariadb
    container_name: mariadb
    # build:
    #   context: ./srcs/mariadb
    #   dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress_db:
  wordpress_html: