version: '3'

services:
  nginx:
    #image: nginx:latest
    build:
      context: ./srcs/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./srcs/nginx/mynginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - inception

  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: inception_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  inception_db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
  db_data:
